spring:
  session:
    store-type: "#{SPRING_SESSION_STORE}"
  http.multipart:
    max-file-size: "#{MULTIPART_FILE_SIZE}"
    max-request-size: "#{MULTIPART_REQUEST_SIZE}"

files:
  version: "#{Octopus.Release.Number}"
  listing.baseDirectory: "#{LISTING_BASEDIR}"
  download.baseUrl: "#{DOWNLOAD_BASEURL}"
  application.base-url: "#{APPLICATION_BASEURL}"

keycloak:
  realm: "#{KEYCLOAK_REALM}"
  auth-server-url: "#{KEYCLOAK_AUTH_SERVER_URL}"
  ssl-required: "#{KEYCLOAK_SSL_REQUIRED}"
  resource: "#{KEYCLOAK_CLIENT_ID}"
  use-resource-role-mappings: true
  public-client: true
  principal-attribute: "#{KEYCLOAK_PRINCIPAL_ATTR}"