spring:
  session:
    store-type: hash_map
  http.multipart:
    max-file-size: "#{MULTIPART_FILE_SIZE}"
    max-request-size: "#{MULTIPART_REQUEST_SIZE}"
security:
  user:
    password: "#{USER_PASSWORD}"
    name: "#{USER_NAME}"

files:
  version: "#{Octopus.Release.Number}"
  listing.baseDirectory: "#{LISTING_BASEDIR}"
  download.baseUrl: "#{DOWNLOAD_BASEURL}"
  application.base-url: "#{APPLICATION_BASEURL}"